### ISSUE TITLE
compatible with missionbio tapestri package : mosaic ?

### ISSUE THREAD

**Issue by reJELIN** [niaid/dsb_manuscript#1]
Hello,

i'm really interested in dsb normalization for one of my project involving missiobion tapestri single-cell data combining DNA and protein.

I was wondering if the package muon package that propose muon was compatible with mosaic package data or if i should somehow transform my protein data into an AnnData structure ?

Thanks you for your response
reJELIN

**Comment by MattPM** [comment]
Hi, This question refers to the dsb R package -- this repository is code to reproduce the manuscript, not the R package. 

For the R package you will want to open an issue on the R package github repository: https://github.com/niaid/dsb If you have further questions please use that repository. 

We describe using dsb with mission bio data in the paper. You can see how we did that in this script https://github.com/niaid/dsb_manuscript/blob/main/V2/missionbio_tapestri/tapestri_exampledata_analysis.r 

You can also probably use muon but I'm not sure if there is a big advantage unless you prefer using python. I'm not sure I know of a way to make an anndata struc out of DNA mutation + Protein data. If you're just trying to normalize the ADTs it will be simpler to use the R package and you can follow the code above to do so.
Best,
Matt

**Comment by reJELIN** [comment]
Hello,

Indeed at the end i refered to your R script analysis and i'm juggling between python and R in order to make it work (mosaic package is develop for python) so after i compute normalization on my read counts i'm transfering it with a csv in order to integrate them with the mosaic package.

Thanks you for your response.
